{% set name = "GladTeX" %}
{% set version = "4.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: e9d6a814bdfd84410f22e94447bcd8df50fd6ddc64c0b61f72f02258b77ea5cc

build:
  number: 0
  noarch: python
  entry_points:
    - gladtex = gleetex.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - gleetex
  commands:
    - pip check
    - gladtex --help
  requires:
    - pip

about:
  home: https://humenda.github.io/GladTeX
  summary: Formula typesetting for the web using LaTeX
  license: AGPL-1.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - ickc
